### ISSUE TITLE
check for $MSYSTEM at the start of every build script

### ISSUE THREAD

**Issue by MaverickTse** [MaverickTse/lsw-build2#13]
currently only buildmypkg(64).sh checks for correct compiler bitness environment before proceeding. Users can however, invoke the wrong build script (bld_*.sh) by hand.

Very easy to implement. Just copy-paste.

**Comment by MaverickTse** [comment]
added you as a collaborator of this repo ＼(^o^)／

**Comment by yumetodo** [comment]
`coreupdate.sh`と`inst_vase.sh`にもcheckは必要では？

``` sh
if [ $MSYSTEM != "MSYS" ]; then
echo "You MUST launch MSYS2 using msys2_shell.bat"
echo "OR set the PROCESS environment variable: MSYSTEM , to 'MSYS', prior launching mintty.exe"
exit
else
```

また、*_64.shですが

``` sh
echo "You MUST launch MSYS2 using mingw64_shell.bat"
echo "OR set the PROCESS environment variable: MSYSTEM , to 'MINGW64', prior launching mintty.exe"
```

にしないとメッセージがおかしい気がします、だよね？神御田(@AinoMegumi)

したがってIssueはreopenするべきです。

・・・ところで`get_patch.sh`は何をしていて、どこで呼ばれているのでしょう・・・・

**Comment by MaverickTse** [comment]
coreupdateはどんなMSYSTEMでも構いません。
inst_baseは最初のSetupしか実行しません

**Comment by MaverickTse** [comment]
たしか　*_64.sh のError messageがおかしいです…　to MINGW32→ to MINGW64

**Comment by MaverickTse** [comment]
actually I found only one file with the wrong error message and I have just fixed that. Please double check.

**Comment by MaverickTse** [comment]
get_patch.sh is called by ./buildmypkg(64).sh

**Comment by yumetodo** [comment]
ああ、おかしいのは`bld_bzip2_64.sh`だけか。じゃあこれでfixedで。

> get_patch.sh is called by ./buildmypkg(64).sh

そこか、ぜんぜん違うところを探していた・・・。

**Comment by MaverickTse** [comment]
I'll just leave this issue opening here for a few days in case we miss something.

**Comment by MaverickTse** [comment]
Extrat "else" without matching "fi" broke some scripts. Fixing...

**Comment by MaverickTse** [comment]
fixed
