### ISSUE TITLE
7zip 15.12

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/lsw-build2#20]
7-Zip 15.12 (2015-11-19) がリリースされました
https://sevenzip.osdn.jp/download.html

対応するべきですか？

**Comment by MaverickTse** [comment]
you can make a patch, but don't merge to master until after New Year. It is a new release after all.

**Comment by yumetodo** [comment]
わかりました

**Comment by yumetodo** [comment]
7-zip 9.20よりあとは、zipで落とせないので対応しないことにする
