### ISSUE TITLE
update-coreコマンドは廃止された

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/lsw-build2#21]
[MSYS2における正しいパッケージの更新方法](http://qiita.com/k-takata/items/373ec7f23d5d7541f982)

現在msys2で入る最新のpacmanは

```
$ pacman -Sl | grep 'pacman '
msys pacman 5.0.1.6403.520736d-1 [インストール済み]
```

5.0.1.6403系のようである。したがって`update-core`コマンドは廃止された。

代わりに

```
pacman -Sy
```

とするべきである。

**Comment by MaverickTse** [comment]
Thanks for noticing. Please test out the proposed patch: https://github.com/MaverickTse/lsw-build2/pull/22 .
