### ISSUE TITLE
TDM-GCC using the new GCC 5.1 fails completely

### ISSUE THREAD

**Issue by MaverickTse** [MaverickTse/lsw-build2#5]
something changed with the command line options, probably... and lead to nothing can be built.

**Comment by MaverickTse** [comment]
temporary fix by forcing to use tdm-gcc v4.9.
In TDM-GCC v5.1, the old way of direct archive extraction seems to give an incorrect folder structure, and result in compiler inability to locate some basic header files.
In the long term, a better way to "install" tdm-gcc is required.

**Comment by yumetodo** [comment]
フォルダー構造が変わってるのか、sh側で移動する必要があるということ？

ところでpacmanでclang入れられるけど、あれではビルドできないのかな・・・

**Comment by MaverickTse** [comment]
clang has a lot of problems building Windows application, but may be my knowledge is outdated... you can try to see if it builds FFmpeg(32 and 64 bit static) correctly.
