### ISSUE TITLE
環境変数HOMEがWin側で定義されていると動作しない

### ISSUE THREAD

**Issue by yumetodo** [MaverickTse/lsw-build2#8]
環境変数`HOME`がWIndows側で定義されているとmsys2の`HOME`もその場所になるため、
`msys64\home\[name]`
にスクリプトがコピーされず環境変数`HOME`で指定されたパスにコピーされる

vbs側でそれに対応できていないのか
`msys64\home\[name]`
からshを探すため失敗する

**Comment by MaverickTse** [comment]
Please try the new branch:
[https://github.com/MaverickTse/lsw-build2/tree/HOME_Fix]

Should have fixed the HOME issue if defined as USER variable (tested in Win7 VM). Not tested if HOME is defined as SYSTEM variable.

I'll wait for your confirmation before merging back to the main branch.

**Comment by yumetodo** [comment]
ユーザー環境変数`HOME`があった場合、　
https://github.com/MaverickTse/lsw-build2/tree/HOME_Fix
は成功しました。
システム環境変数`HOME`があった場合
も成功しました。

念のため理科大で検証してきます

**Comment by MaverickTse** [comment]
Fixes merged back to master branch
[https://github.com/MaverickTse/lsw-build2/pull/9]
